export const MONSTERS_FETCH = 'MONSTERS_FETCH';
export const MONSTERS_RESULT = 'MONSTERS_RESULT';
export const MONSTERS_ERROR = 'MONSTERS_ERROR';

export const MONSTER_DETAILS_FETCH = 'MONSTER_DETAILS_FETCH';
export const MONSTER_DETAILS_RESULT = 'MONSTER_DETAILS_RESULT';
export const MONSTER_DETAILS_ERROR = 'MONSTER_DETAILS_ERROR';

export const MONSTER_CLEAR_SELECTED = 'MONSTER_CLEAR_SELECTED';

export const MONSTER_DELETE_SUBMIT = 'MONSTER_DELETE_SUBMIT';
export const MONSTER_DELETE_ERROR = 'MONSTER_DELETE_ERROR';
export const MONSTER_DELETE_RESULT = 'MONSTER_DELETE_RESULT';

export const MONSTER_CREATE_SHOW = 'MONSTER_CREATE_SHOW';
export const MONSTER_CREATE_SUBMIT = 'MONSTER_CREATE_SUBMIT';
export const MONSTER_CREATE_ERROR = 'MONSTER_CREATE_ERROR';
export const MONSTER_CREATE_RESULT = 'MONSTER_CREATE_RESULT';

export const MONSTER_EDIT_SHOW = 'MONSTER_EDIT_SHOW';
export const MONSTER_EDIT_SUBMIT = 'MONSTER_EDIT_SUBMIT';
export const MONSTER_EDIT_ERROR = 'MONSTER_EDIT_ERROR';
export const MONSTER_EDIT_RESULT = 'MONSTER_EDIT_RESULT';

export const MODAL_CLOSE = 'MODAL_CLOSE';
