export const MONSTERS_FETCH = 'MONSTERS_FETCH';
export const MONSTERS_RESULT = 'MONSTERS_RESULT';
export const MONSTERS_ERROR = 'MONSTERS_ERROR';

export const MONSTER_DETAILS_FETCH = 'MONSTER_DETAILS_FETCH';
export const MONSTER_DETAILS_RESULT = 'MONSTER_DETAILS_RESULT';
export const MONSTER_DETAILS_ERROR = 'MONSTER_DETAILS_ERROR';

export const MONSTER_CLEAR_SELECTED = 'MONSTER_CLEAR_SELECTED';
